### PR TITLE
Dutch translation for review

### PR DESCRIPTION
**Pull request by ProkhorZ**
This is the Dutch translation of all kovri-docs files including the most recent updates: 
- English: update tunnel setup in user guide - PR #91
- English: fix SIGHUP command in monero guide - PR #93

Hallo @skftn @rpcjacobs @keesieboy @lckarssen @fridzema @potatored!
I want to ask Dutch-speaking contributors for advice about some key style and terminology issues before submitting my translation. Today I learned the Kovri repos moved to GitLab, but you can comment here if you haven't moved yet.

Please write reviews in English, so that maintainers and other contributors can follow what you're talking about.

Questions:

1. While we use a formal form of address in the GUI, giving technical instructions to developers and power users is a less formal context than a wallet that anyone could use. And these documents are written in an informal style. I started by using 'u', but it felt unnatural, and I changed it to 'je'. Do you agree? German uses 'du', while French uses 'vous'.

2. How do you call people working on the Kovri project? We can't say 'medewerkers', because that means employees. The literal translations I used seem unnatural:
*contributor = bijdrager*
*collaborator = samenwerker*

3. The verb *build = compileren?* It may not be exactly the same, but alternatives like 'opbouwen' would be unnatural, literal translations. We don't use that metaphor in this context. (The noun *build* can be left untranslated, I think.)

4. *Refactor = code opschonen/herstructureren*? (developer guide)

5. *During setup = tijdens het installeren/configureren?* (testnet guide)

6. *Preliminaries = Vooraf?* (Heading in code of conduct)

7. Any other comments?

Notes:

1. Unlike the source text, I use a period after bullet points when at least one of them in the list includes a full sentence. So that's a different style, not a mistake. A full sentence is one which includes a verb in the indicative or imperative mode (*persoonsvorm* in Dutch).

2. In the code of conduct, SHOULD has a [specific meaning](https://github.com/monero-project/kovri-docs/issues/100), so it can't be translated with MOET. That's why I chose HOORT TE for the concept 'recommended but not compulsory'.

3. "Note: ..." has been translated as "Opmerking: ..." I'm not using the more correct translation "Let op: ..." because it would give more emphasis than is required for these notes.

### CODE REVIEW

**Comment by Alex058-2** [comment]
Hi,

Q1: I agree the formal form doesn't work, I agree with "je"
Q2: The Dutch language has no good word for _contributor_, I'd prob prefer "vrijwilliger" (=volunteer)
Q3: agree
Q4: the Dutch wiki uses "herstructureren" in combination with the goal to simplify, so I guess "herstructureren" would be fine
Q5: I'd prefer "configureren", because setup translated in Dutch is "opstelling"; I feel this comes very close  configuration
Q6: "Vooraf" would be ok, or maybe "Inleiding"

Thanks so far for your efforts, I'll try and have a look at the Kovri docs asap.

**Comment by ProkhorZ** [comment]
Feedback from IRC:
- Agree with *je*.
- *Compileren* is OK.
- Leave words like 'refactor' that are difficult to translate in English.

**Comment by ProkhorZ** [comment]
There's also a merge request on GitLab now. I haven't changed anything yet, except one missing `tick`:

https://gitlab.com/kovri-project/kovri-docs/merge_requests/102

TIL GitLab saves merge requests under the target branch.

**Comment by lckarssen** [comment]
Thanks for working on this @ProkhorZ! In general I agree with the above. My 2 cents:

Q1: agree
Q2: I'm a bit ambiguous about this one. I personally don't think a _'medewerker'_ is per definition an employee. My rather old (1984) Van Dale dictionary lists _'werkkracht, functionaris'_ as second meaning of _'medewerker'_ and _'iemand die meewerkt, bijv. aan een tijdschrift enz.'_ as first. My Van Dale EN dictionary lists _'bijdrager', 'contribuant'_ and _'medewerker'_ as possible translations for contributor. 
All in all I guess the suggested _'vrijwilliger'_ is best.
Q3: _Compileren_ is OK
Q4: _refactor_ is OK
Q5: I agree with _'configureren'_. About the 'setup' being translated as 'opstelling': although that is a correct translation, the use of the noun 'setup' in this part of the documentation is different from 'opstelling', we are not talking about a machine or measurement or camera setup, for example. In this case the meaning is that of _'opzetten, instellen, monteren, plaatsen, in elkaar zetten'_.
Q6: How about "Woord vooraf"? I think this is the usual term in Dutch. 

About the notes:
N1: Totally agree
N2: Agree
N3: Agree.

**Comment by ProkhorZ** [comment]
Good news: the translation has already been merged on GitLab! But we can still keep improving the text.

Thanks for the feedback, Alex and Lennart.

> I personally don't think a 'medewerker' is by definition an employee. 

You're right, I forgot about that meaning. And *vrijwilliger* also suggests too much about employment status. Some contributors do work for a Monero-related company.

*Off-topic note: the Grote Van Dale is a historical dictionary, which lists the oldest meaning first, not the most common meaning. It's an excellent dictionary if your goal is to understand 19th century novels.*

I consider the following questions settled: 

Q1: you = je
Q3: to build = compileren
Q5: during setup = tijdens het configureren

**Comment by Alex058-2** [comment]
Hi Edwin,

Thats very good news, well done and thanks!

Kind regards,
Alex

**Comment by ProkhorZ** [comment]
There's a new Dutch translation to review: I also translated Monerujo, the Android app.
https://github.com/m2049r/xmrwallet/pull/411

**Comment by ProkhorZ** [comment]
The website content for kovri.io has also been translated into Dutch.
Discussion: https://gitlab.com/kovri-project/kovri-site/merge_requests/123
Except for the language code, it's one file: https://gitlab.com/ProkhorZ/kovri-site/raw/ad938ce9c61cdd659e76c3ffee43a1d7c78b52ad/kovri.i2p/_i18n/nl.yml

Who wants to review this on GitLab? And by reviewing I mean determining whether the translation is good enough to be published. Commenting on details is also useful, but we can improve details at any moment.

**Pull request closed without merging**
